#pragma once

#define RGBLIGHT_DEFAULT_HUE    15
#define RGBLIGHT_DEFAULT_SAT    255
#define RGBLIGHT_DEFAULT_VAL    128
#define RGBLIGHT_DEFAULT_MODE   RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_HUE_STEP       5
#define RGBLIGHT_LIMIT_VAL      180
#define RGBLIGHT_SLEEP